[setup]
# Aquí obligamos a instalar Node, Python y Pip explícitamente
pkgs = ["nodejs_22", "python311", "python311Packages.pip"]

[install]
# Instalamos Node normalmente. 
# Si no tienes requirements.txt, este comando no fallará.
cmds = ["npm install"]

[start]
# Tu comando para iniciar el servidor
cmd = "node index.js"
